# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_csv": "01_df_split_offline_online.ipynb",
         "split_offline_online": "01_df_split_offline_online.ipynb",
         "DATE_SPLIT": "01_df_split_offline_online.ipynb",
         "clean_data": "02_df_clean_rows.ipynb"}

modules = ["df/load_split.py",
           "dataframe/split.py"]

doc_url = "https://team2.github.io/elab2team2/"

git_url = "https://github.com/artemlops/elab2team2/tree/master/"

def custom_doc_links(name): return None
