# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_csv": "01_data_split_offline_online.ipynb",
         "split_offline_online": "01_data_split_offline_online.ipynb",
         "DATE_SPLIT": "01_data_split_offline_online.ipynb",
         "clean_drop_na": "02_data_clean_rows.ipynb",
         "clean_drop_duplicates": "02_data_clean_rows.ipynb",
         "clean_remove_bad_order_cancellations": "02_data_clean_rows.ipynb",
         "clean_data_rows": "02_data_clean_rows.ipynb",
         "build_product_list": "03_data_analyse_keywords.ipynb",
         "plot_product_list_histogram": "03_data_analyse_keywords.ipynb",
         "build_keywords_matrix": "03_data_analyse_keywords.ipynb",
         "display_keywords_matrix": "03_data_analyse_keywords.ipynb"}

modules = ["data/load_split.py",
           "data/clean_rows.py",
           "data/analyse_keywords.py"]

doc_url = "https://featurologists-team.github.io/featurologists/"

git_url = "https://github.com/artemlops/elab-2-team2/tree/master/"

def custom_doc_links(name): return None
