# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_data_csv": "00_data_zoo.ipynb",
         "BASE_URL": "00_data_zoo.ipynb",
         "SUPPORTED_SUFFIXES": "00_data_zoo.ipynb",
         "load_data_csv": "01_split_offline_online.ipynb",
         "split_by_invoice_date": "01_split_offline_online.ipynb",
         "DATE_SPLIT": "01_split_offline_online.ipynb",
         "clean_drop_na": "02_clean_rows.ipynb",
         "clean_drop_duplicates": "02_clean_rows.ipynb",
         "clean_remove_bad_order_cancellations": "02_clean_rows.ipynb",
         "clean_data_rows": "02_clean_rows.ipynb",
         "build_product_list": "03_analyse_purchases.ipynb",
         "plot_product_list_histogram": "03_analyse_purchases.ipynb",
         "build_keywords_matrix": "03_analyse_purchases.ipynb",
         "display_keywords_matrix": "03_analyse_purchases.ipynb",
         "compute_purchase_clusters": "03_analyse_purchases.ipynb",
         "plot_silhouette": "03_analyse_purchases.ipynb",
         "add_purchase_clusters_info": "03_analyse_purchases.ipynb",
         "build_transactions_per_user": "04_analyse_customers.ipynb",
         "compute_n_customers_with_unique_purchase": "04_analyse_customers.ipynb",
         "convert_customers_df_to_np": "04_analyse_customers.ipynb",
         "analyse_customers_pca": "04_analyse_customers.ipynb",
         "plot_customers_pca": "04_analyse_customers.ipynb",
         "compute_customer_clusters": "04_analyse_customers.ipynb",
         "plot_customer_categories": "04_analyse_customers.ipynb",
         "add_customer_clusters_info": "04_analyse_customers.ipynb",
         "compute_aggregated_customer_clusters_info": "04_analyse_customers.ipynb"}

modules = ["data_zoo.py",
           "load_split.py",
           "clean_rows.py",
           "analyse_purchases.py",
           "analyse_customers.py"]

doc_url = "https://artemlops.github.io/customer-segmentation-toolkit/customer-segmentation-toolkit/"

git_url = "https://github.com/artemlops/customer-segmentation-toolkit/tree/master/"

def custom_doc_links(name): return None
